version: '3.8'

networks:
  inception:

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
         - DB_NAME=${DB_NAME}
         - DB_USER=${DB_USER}
         - DB_PASSWORD=${DB_PASSWORD}
         - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_vol:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress_vol:/var/www/wordpress
    depends_on:
      - wordpress
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    restart: unless-stopped

volumes:
    mariadb_vol:
      driver: local
      driver_opts:
        device: "/home/jechoo/data/mariadb"
        type: none
        o: bind
    wordpress_vol:
      driver: local
      driver_opts:
        type: none
        device: "/home/jechoo/data/wordpress"
        o: bind