version: '3.7'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html # Adjusted to match the expected directory structure
    depends_on:
      - wordpress
      - mariadb
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html # Ensure this matches your WordPress/nginx root
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  wordpress_data: # This volume is shared between WordPress and NGINX
  db_data:

networks:
  default:
